export enum LoadersId {
  IS_CREATING_CLASSROOM = 'IS_CREATING_CLASSROOM',
  IS_DELETING_CLASSROOM = 'IS_DELETING_CLASSROOM',
  IS_CREATING_STUDENT = 'IS_CREATING_STUDENT',
  IS_DELETING_STUDENT = 'IS_DELETING_STUDENT',
}
